import AudioPlayButton from "@/components/common/AudioPlayButton";
import { useGenerateAudioMutation } from "@/apis/chat/chatApi";
import FormattedText from "./FormatedText";
import LoadingSkeleton from "@/components/common/LoadingSkelton";

const ResourceList = ({ aiResponse, isLoading }) => {
  const { mutate: generateAudio, isPending } = useGenerateAudioMutation();

  const cleanText = aiResponse?.startsWith("This response generated by AI")
    ? aiResponse.split("\n").slice(1).join("\n").trim()
    : aiResponse;

  if (isLoading) return <LoadingSkeleton />;

  return (
    <div className="bg-gray-50 rounded-lg shadow-sm p-6">
      {cleanText ? (
        <div className="mb-6 bg-white rounded-lg p-6 shadow-sm border border-gray-200">
          <div className="text-gray-700 mb-4">
            <FormattedText text={cleanText} />
          </div>
          <div className="flex justify-end">
            <AudioPlayButton
              text={cleanText}
              generateAudio={generateAudio}
              loading={isPending}
              buttonClass="text-blue-600 hover:text-blue-800"
            />
          </div>
        </div>
      ) : (
        <div className="text-center py-8">
          <h3 className="text-lg font-medium text-gray-900 mb-2">
            Coming Soon
          </h3>
        </div>
      )}
    </div>
  );
};
export default ResourceList;
